### ISSUE TITLE
Works on Firefox, but not on google chrome

### ISSUE THREAD

**Issue by Naruto-Man** [CezaryDanielNowak/Blur.js#2]
It only work on Firefox and when i tried it on Google chrome it make an exception "cannot access local image" so what is going on ? And how to fix this ?

**Comment by CezaryDanielNowak** [comment]
This may be related with privacy policy, when use `file://` links. Could you provide some more info,  sample jsfiddle ? :-)

**Comment by CezaryDanielNowak** [comment]
@Naruto-Man I'm closing this issue. I hope, you're fine :-P
