### ISSUE TITLE
Blur effect not as smooth as in the original blur.js

### ISSUE THREAD

**Issue by pweix** [CezaryDanielNowak/Blur.js#3]
It's great that you can blur multiple images with this fork, thanks for that!

But when I switched the original library to your fork I recognised, that the blur effect with a higher radius are not as smooth as with the original library (see attached images - radius was 15 and the exact same parameters). Do you have any idea why this could be the case? I could try to fix it myself, if you could give me some pointers but I'm certainly no javascript expert :( 

![screenshot 2015-08-29 20 47 31](https://cloud.githubusercontent.com/assets/676195/9563778/b725261a-4e8f-11e5-8352-1abfd887b31d.png)
![screenshot 2015-08-29 20 47 40](https://cloud.githubusercontent.com/assets/676195/9563779/b7272186-4e8f-11e5-88b7-7cb2c851ff26.png)

Here is the function call I use:

```
$('.blurred_cover_img').blurjs({
    source: '#cover-img-src',
    radius: 15,
    overlay: 'rgba(0,0,0,0.3)'
});
```

**Comment by CezaryDanielNowak** [comment]
Hey @Wexoo :)
I switched default blur algo cause of better performance, especially for lots of images. You still can use old one:
- dist/jquery.blur.js is slower but prettier
- dist/jquery.stack-box-blur.js is faster but uglier

Please let me know if switching helped
