### ISSUE TITLE
Hello very nice work!

### ISSUE THREAD

**Issue by dasi1va** [CezaryDanielNowak/Blur.js#4]
Hello very nice work! I want create multiple images blur loaded dynamically when selected list but when select new image the last blur removed is there any way keep all blurred?

**Comment by CezaryDanielNowak** [comment]
Please provide demo on jsfiddle or similar service. I don't see why adding new blur could remove old one :-)

**Comment by dasi1va** [comment]
Hello I have fixed with just add img tag except background image! thanks
